### ISSUE TITLE
removal of ports gives issues

### ISSUE THREAD

**Issue by edwinmat** [ESDLMapEditorESSIM/esdl-mapeditor#7]

**Comment by ewoudwerkman** [comment]
Ik heb de bug opgelost voor het deleten van poorten van een lijn. Dit wissen was niet ondersteund (met reden 😉, zie hieronder) 
Bij de volgende update van de MapEditor wordt dit meegenomen (versie 21.5.2 (zie Help->About)).

In principe is het wissen van een poort van een lijn (pijp of kabel) geen goed idee, omdat je dan een pijp maakt waarvan 1 kant dichtgelast is 😉. Maar goed, een MapEditor die niet werkt is ook geen goed idee. 
Ik heb aangepast dat je ook weer een poort kan toevoegen (dit was voor pijpen niet geimplementeerd), met een maximum van 2.
Let op dat als je de InPort poort van een pijp wist, je een rare situatie krijgt dat de OutPort nu verwijst naar het eerste coordinaat van een pijp (dat is de conventie die we hebben afgesproken bij het visualiseren van een pijp in de mapeditor). Als je dan weer een InPort toevoegd, gedraagd de pijp zich weer normaal. Een pijp met twee outports of twee inports is niet mogelijk in de MapEditor en wordt nu afgevangen.

**Comment by ewoudwerkman** [comment]
Fixed in 21.5.2
